spring:
  application:
  name: basicsec
  security:
    user:
        name: user
        password: password
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  app:
    jwtSecret: here-is-secret
    jwtExpiration: 3600000 #1h